-- 创建邮件用户表
CREATE TABLE IF NOT EXISTS mail_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(32) NOT NULL,
  email VARCHAR(100) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_mail_users_status ON mail_users(status);
